services:
  - type: web
    name: malta-info-bot-backend
    env: python
    buildCommand: ""
    startCommand: python app.py
    plan: free
    envVars:
      - key: GEMINI_API_KEY
        value: la_tua_api_key
